# Generated by Django 4.1.2 on 2023-04-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("score", models.IntegerField()),
                ("wins", models.IntegerField()),
                ("loses", models.IntegerField()),
                ("draws", models.IntegerField()),
            ],
        ),
    ]
