# Generated by Django 4.1.2 on 2023-04-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="draws",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="loses",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="score",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="wins",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
