# Generated by Django 4.1.2 on 2023-04-26 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0002_alter_player_draws_alter_player_loses_and_more"),
        ("match", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winner",
                to="player.player",
            ),
        ),
    ]
